In [180]:
import pandas as pd
import numpy as np

In [181]:
df = pd.read_csv('AllMailsOut.csv')  

In [182]:
df.shape

(21426, 6)

In [183]:
df.head()

ID                      FROMEMAIL  \
0  1  Edi [BCTN]" <bctedi@bctn.eu>"   
1  2                  edidft@icg.ie   
2  3                  edidft@icg.ie   
3  4              edi@terminalas.lt   
4  5        RCT <edi.rigact@rto.lv>   

                                             SUBJECT  \
0  Daily move ROE - Samskip Multimodal B.V. 15-11...   
1                        DFT CODECO file for SAMSKIP   
2                        DFT CODECO file for SAMSKIP   
3                        KCT SAMSKIP CODECO MESSAGES   
4                     Container  SANU7524842 arrived   

                                                BODY NOATT  \
0  \nThis email is generated automatically. Pleas...     2   
1  \nThis message was automatically generated.\n\...     2   
2  \nThis message was automatically generated.\n\...     2   
3  \nDear Sir or Madam,\r\n\r\nWe are sending new...     3   
4  \nUNA:+.? '\r\nUNB+UNOE:2+LVRIXRCOT+ISREYSANA+...     1   

                      ATTFILES  
0    ROE20221115133351477.txt;  
1              0000984742.txt;  
2              0000984741.txt;  
3  Samskip-CODECO04097126.EDI;  
4         truck_in_457930.edi;

In [184]:
df.isnull().sum()

ID              0
FROMEMAIL      48
SUBJECT       226
BODY         2302
NOATT         270
ATTFILES      434
dtype: int64

In [185]:
df['adrress']=1

In [186]:
df['output']=1

In [187]:
df['ATTFILESLIST'] = df['ATTFILES'].str.split(";")

In [188]:
df['ATTCOUNT'] = df['ATTFILESLIST'].str.len()-1

In [189]:
df['ATTCOUNT'] = df['ATTCOUNT'].replace(0,np.NaN)

In [190]:
df[df['ATTCOUNT'].isna()]['ATTCOUNT'] =0

/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/3131770928.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['ATTCOUNT'].isna()]['ATTCOUNT'] =0


In [191]:
df['ATTCOUNT']= df['ATTCOUNT'].fillna(0)

In [192]:
df['ATTCOUNT'].isna().sum()

0

In [193]:
df['ATTCOUNT'] = df['ATTCOUNT'].astype(int)

In [194]:
df['FROMEMAIL'].loc[~df['FROMEMAIL'].isna()] = 1  # not nan
df['FROMEMAIL'].loc[df['FROMEMAIL'].isna()] = 0 

/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/316474879.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FROMEMAIL'].loc[~df['FROMEMAIL'].isna()] = 1  # not nan
/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/316474879.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FROMEMAIL'].loc[df['FROMEMAIL'].isna()] = 0


In [195]:
df['FROMEMAIL'].value_counts()

1    21378
0       48
Name: FROMEMAIL, dtype: int64

In [196]:
df.head()

ID FROMEMAIL                                            SUBJECT  \
0  1         1  Daily move ROE - Samskip Multimodal B.V. 15-11...   
1  2         1                        DFT CODECO file for SAMSKIP   
2  3         1                        DFT CODECO file for SAMSKIP   
3  4         1                        KCT SAMSKIP CODECO MESSAGES   
4  5         1                     Container  SANU7524842 arrived   

                                                BODY NOATT  \
0  \nThis email is generated automatically. Pleas...     2   
1  \nThis message was automatically generated.\n\...     2   
2  \nThis message was automatically generated.\n\...     2   
3  \nDear Sir or Madam,\r\n\r\nWe are sending new...     3   
4  \nUNA:+.? '\r\nUNB+UNOE:2+LVRIXRCOT+ISREYSANA+...     1   

                      ATTFILES  adrress  output  \
0    ROE20221115133351477.txt;        1       1   
1              0000984742.txt;        1       1   
2              0000984741.txt;        1       1   
3  Samskip-CODECO04097126.EDI;        1       1   
4         truck_in_457930.edi;        1       1   

                     ATTFILESLIST  ATTCOUNT  
0    [ROE20221115133351477.txt, ]         1  
1              [0000984742.txt, ]         1  
2              [0000984741.txt, ]         1  
3  [Samskip-CODECO04097126.EDI, ]         1  
4         [truck_in_457930.edi, ]         1

In [197]:
spam = pd.read_csv('enron_spam_data.csv')  

In [198]:
spam.head()

Message ID                       Subject  \
0           0  christmas tree farm pictures   
1           1      vastar resources , inc .   
2           2  calpine daily gas nomination   
3           3                    re : issue   
4           4     meter 7268 nov allocation   

                                             Message Spam/Ham        Date  
0                                                NaN      ham  1999-12-10  
1  gary , production from the high island larger ...      ham  1999-12-13  
2             - calpine daily gas nomination 1 . doc      ham  1999-12-14  
3  fyi - see note below - already done .\nstella\...      ham  1999-12-14  
4  fyi .\n- - - - - - - - - - - - - - - - - - - -...      ham  1999-12-14

In [199]:
spam[spam['Spam/Ham']=='spam'].shape

(17171, 5)

In [200]:
spamn = spam[spam['Spam/Ham']=='spam']

In [201]:
spamn.shape

(17171, 5)

In [202]:
spamn['Output'] =0


/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/1880172014.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spamn['Output'] =0


In [203]:
spamn['ATTCOUNT'] =0
spamn['FROMEMAIL'] =0

/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/2617437242.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spamn['ATTCOUNT'] =0
/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/2617437242.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spamn['FROMEMAIL'] =0


In [204]:
spamn.head()

Message ID                                            Subject  \
3672        3672  dobmeos with hgh my energy level has gone up !...   
3673        3673          your prescription is ready . . oxwq s f e   
3674        3674                              get that new car 8434   
3675        3675                                await your response   
3676        3676  coca cola , mbna america , nascar partner with...   

                                                Message Spam/Ham        Date  \
3672  introducing\ndoctor - formulated\nhgh\nhuman g...     spam  2003-12-18   
3673  low cost prescription medications\nsoma , ultr...     spam  2003-12-18   
3674  people nowthe weather or climate in any partic...     spam  2003-12-18   
3675  dear partner ,\nwe are a team of government of...     spam  2003-12-18   
3676  stock\nprofile\nabout\ncompany\ninvestment\nhi...     spam  2003-12-18   

      Output  ATTCOUNT  FROMEMAIL  
3672       0         0          0  
3673       0         0          0  
3674       0         0          0  
3675       0         0          0  
3676       0         0          0

In [205]:
spamn.rename({'Subject': 'SUBJECT', 'Message': 'BODY','Output':'output'}, axis=1, inplace=True)

/var/folders/0x/hjdrdw650pqchzql_74mksxm0000gp/T/ipykernel_21887/4036986947.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spamn.rename({'Subject': 'SUBJECT', 'Message': 'BODY','Output':'output'}, axis=1, inplace=True)


In [206]:
spamn.head()

Message ID                                            SUBJECT  \
3672        3672  dobmeos with hgh my energy level has gone up !...   
3673        3673          your prescription is ready . . oxwq s f e   
3674        3674                              get that new car 8434   
3675        3675                                await your response   
3676        3676  coca cola , mbna america , nascar partner with...   

                                                   BODY Spam/Ham        Date  \
3672  introducing\ndoctor - formulated\nhgh\nhuman g...     spam  2003-12-18   
3673  low cost prescription medications\nsoma , ultr...     spam  2003-12-18   
3674  people nowthe weather or climate in any partic...     spam  2003-12-18   
3675  dear partner ,\nwe are a team of government of...     spam  2003-12-18   
3676  stock\nprofile\nabout\ncompany\ninvestment\nhi...     spam  2003-12-18   

      output  ATTCOUNT  FROMEMAIL  
3672       0         0          0  
3673       0         0          0  
3674       0         0          0  
3675       0         0          0  
3676       0         0          0

In [207]:
final1 = df[['FROMEMAIL','ATTCOUNT','SUBJECT','BODY','output']]

In [208]:
final1.head()

FROMEMAIL  ATTCOUNT                                            SUBJECT  \
0         1         1  Daily move ROE - Samskip Multimodal B.V. 15-11...   
1         1         1                        DFT CODECO file for SAMSKIP   
2         1         1                        DFT CODECO file for SAMSKIP   
3         1         1                        KCT SAMSKIP CODECO MESSAGES   
4         1         1                     Container  SANU7524842 arrived   

                                                BODY  output  
0  \nThis email is generated automatically. Pleas...       1  
1  \nThis message was automatically generated.\n\...       1  
2  \nThis message was automatically generated.\n\...       1  
3  \nDear Sir or Madam,\r\n\r\nWe are sending new...       1  
4  \nUNA:+.? '\r\nUNB+UNOE:2+LVRIXRCOT+ISREYSANA+...       1

In [209]:
final2 = spamn[['FROMEMAIL','ATTCOUNT','SUBJECT','BODY','output']]

In [210]:
fintot = pd.concat([final1, final2], ignore_index=True)

In [211]:
fintot.shape

(38597, 5)

In [212]:
fintot.describe()

ATTCOUNT        output
count  38597.000000  38597.000000
mean       0.543876      0.555121
std        0.498078      0.496959
min        0.000000      0.000000
25%        0.000000      0.000000
50%        1.000000      1.000000
75%        1.000000      1.000000
max        1.000000      1.000000

In [213]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.dummy import DummyClassifier, DummyRegressor
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

categorical_feats = ['SUBJECT','BODY']
ct = ColumnTransformer(
    [
        ("onehot", OneHotEncoder(sparse=False), categorical_feats)
    ]
)


In [217]:
from sklearn.model_selection import train_test_split


X = fintot.drop('output', axis=1)
Y = fintot['output']

X = ct.fit_transform(X)

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25)


In [218]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [220]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB()

In [221]:
y_pred = clf.predict(X_test)

In [222]:
clf.score(X_test,y_test)

0.7558549222797928

In [223]:
y_pred 

array([1, 1, 1, ..., 1, 1, 1])

In [224]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1865, 2356],
       [   0, 5429]])

In [227]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       1.00      0.44      0.61      4221
     class 1       0.70      1.00      0.82      5429

    accuracy                           0.76      9650
   macro avg       0.85      0.72      0.72      9650
weighted avg       0.83      0.76      0.73      9650

